Update migration.md
l3tnun/docker-mirakurun-epgstation pull request #20
Opened 2021-01-11 13:49 UTC by 5ym

migrationの誤表記と更新手順の追加を行いました。

2021-01-12 13:14 UTC, l3tnun requested changes

2021-01-12 13:14 UTC, l3tnun commented on epgstation/config/config.sample.yml
> +                 - name: 720p (arib)
実はまだ ffmpeg が aribb24 に対応できた状態でビルドできていないので
この部分はコメントアウトに戻してほしいです。

2021-01-12 13:14 UTC, l3tnun commented
いつもありがとうございます。助かります。

2021-01-12 13:25 UTC, 5ym commented on epgstation/config/config.sample.yml
> +                 - name: 720p (arib)
すみません自分の環境で調整していたものが入ってしまっていました修正いたしますちなみにコメントアウトされていないaribb24を使用しているものはそのままで大丈夫でしょうか

2021-01-12 22:36 UTC, l3tnun commented on epgstation/config/config.sample.yml
> +                 - name: 720p (arib)
> ちなみにコメントアウトされていないaribb24を使用しているものはそのままで大丈夫でしょうか

見落としてました。その部分もコメントアウトお願いします

2021-01-13 08:42 UTC, 5ym commented
修正いたしました。
また別途質問なのですが、`video`のほうでandroidがmx playerを使っていると思うのですが、vlcを利用していない理由等ありますでしょうか

2021-01-13 10:39 UTC, l3tnun commented
修正ありがとうございます。マージします。

>`video`のほうでandroidがmx playerを使っていると思うのですが、vlcを利用していない理由等ありますでしょうか

確か vlc だと、 ts のシークが正常に出来なかったと記憶しています。故にmx playerの設定になっています。

2021-01-13 10:39 UTC, merged